apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: danlevypro/gw:1.0
          ports:
            - containerPort: 80
          imagePullPolicy: Always

          resources:
            limits:
              cpu: '500m'
              memory: '128Mi'
            requests:
              cpu: '250m'
              memory: '64Mi'
